version: '3'
services:
  frontend:
    container_name: labtrack-frontend
    image: labtrack-frontend
    build:
      context: ./Front-End/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    logging:
      driver: "none"
    depends_on:
      - backend

  backend:
    container_name: labtrack-backend
    image: labtrack-backend
    build:
      context: ./Back-End/
      dockerfile: Dockerfile
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - DOCKER=true
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./volumes/data:/data/db
      - ./volumes/logs:/usr/log
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    logging:
      driver: "none"
    command: mongod --quiet --logpath /usr/log/mongodb.log --logappend
