version: '3'
services:
  api:
    container_name: labtrack-backend
    image: labtrack-backend
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    env_file: ../.env
    volumes:
      - ../volumes/logs:/app/logs
      - ../volumes/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - DOCKER=true
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: ../.env
    volumes:
      - ../volumes/data:/data/db
      - ../volumes/mongodb-logs:/usr/log
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    logging:
      driver: "none"
    command: mongod --quiet --logpath /usr/log/mongodb.log --logappend
