version: '3'
services:
  api:
    container_name: labtrack-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - DOCKER=true

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    logging:
      driver: "none"
    command: mongod --quiet --logpath /dev/null
