name: Build and Publish FE Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  FE_REPO_NAME: ${{secrets.FE_REPO_NAME}}

jobs:
  build-and-publish-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN

      - name: Get the current commit hash
        id: get_commit_hash
        run: echo ::set-env name=COMMIT_HASH::$(git rev-parse --short HEAD)

      - name: Build and tag the frontend image
        run: |
          docker build ./Front-End -f ./Front-End/Docker/Dockerfile -t $DOCKER_USER/$FE_REPO_NAME:$COMMIT_HASH
          docker tag $DOCKER_USER/$FE_REPO_NAME:$COMMIT_HASH $DOCKER_USER/$FE_REPO_NAME:latest

      - name: Push the frontend image
        run: |
          docker push $DOCKER_USER/$FE_REPO_NAME:$COMMIT_HASH
          docker push $DOCKER_USER/$FE_REPO_NAME:latest
